name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres: 
        image: postgres:12
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with: 
        profile: minimal
        toolchain: stable
        override: true
    - run: rustup component add clippy
    - uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Migrate database
      run: |
        sudo apt-get install libpq-dev -y
        cargo install --version=0.2.0 sqlx-cli --no-default-features --features postgres
        SKIP_DOCKER=true ./scripts/init_db.sh
    - uses: actions-rs/cargo@v1
      with: 
        command: clippy
        args: -- -D warnings
    - name: Install cargo fmt
      run: rustup component add rustfmt
    - name: Run formatter
      run: cargo fmt -- --check
    - name: Install cargo audit
      run: cargo install cargo-audit
    - name: Check vulnerabilities
      run: cargo audit
